densty_filter:
    meank: 50
    std_hresh: 0.01

crop:
    X_max: 0.8
    X_min: 0.25
    Y_max: 0.2
    Y_min: -0.38
    Z_max: 0.5
    Z_min: 0.28

remove_clster:
    sampel_num: 5
    min_dis: 0.001
    min_clsters: 2

cluster_indices:
    MinClusterSize: 290
    MaxClusterSize: 25000
    ClusterTolerance: 0.01

segmentation_object:
    MaxIterations: 100
    DistanceThreshold: 0.02

